name: Build and Deploy Application

on:
  push:
    paths:
      - 'app/**'
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'app/**'
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build-image.outputs.image-tag }}
      image-uri: ${{ steps.build-image.outputs.image-uri }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public
        mask-password: 'true'

    - name: Build and push Docker image
      id: build-image
      working-directory: ./app
      run: |
        # Generate image tag using git commit SHA and timestamp
        IMAGE_TAG="${GITHUB_SHA:0:8}-$(date +%s)"
        IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

        echo "Building image: $IMAGE_URI"

        # Build the Docker image
        docker build -t $IMAGE_URI .

        # Push the image to ECR
        docker push $IMAGE_URI

        # Also tag and push as latest
        docker tag $IMAGE_URI $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest


# Step 4.1: Login to Amazon ECR
- name: Login to Amazon ECR
  run: |
    aws ecr get-login-password --region $AWS_REGION \
    | docker login --username AWS --password-stdin ${{ env.AWS_REGISTRY_URL }}

# Step 4.2: Build Docker image and tag it
- name: Build Docker image and tag it
  run: |
    echo "Building Docker image with tag: $TAG"
    docker build -t "${{ env.REPOSITORY_NAME }}" .
    docker tag "${{ env.REPOSITORY_NAME }}" "${{ env.AWS_REGISTRY_URL }}/${{ env.REPOSITORY_NAME }}:$TAG"

# Step 4.3: Push Docker image to Amazon ECR
- name: Push Docker image to Amazon ECR
  run: |
    docker push "${{ env.AWS_REGISTRY_URL }}/${{ env.REPOSITORY_NAME }}:$TAG"